label bar:
    hide screen worldmap
    show screen vnui
    if forestroute1 == 0:
        if rikunamed == 0 or buttersnamed == 0 or creamnamed == 0 or aurnamed == 0 or selnamed == 0:
            call v3renames from _call_v3renames_2
        jump bar
    play music butterstheme1 fadein 1
    scene bg forest1
    with d
    menu barmenu:
        "Returning to Butters is in development since it'll directly follow into her next story event."
        "Sex (In Development)":
            jump barmenu
        "Replay Events":
            menu:
                "While replaying, you can return at any time using the phone."
                "Back":
                    pass
        "Leave":
            jump worldmap
    jump butmenu

label bar1:
    "Today is the perfect night to search for [rik]. I just got a message from [pen]: ‘I heard [rik] frequents The Old Mill. Quite a fuss for a celebrity to be in a small place like that. She’s still a big deal.’"
    "I read the text with a faint smile. The Old Mill is the bar the other [rik] owned. Of course, back there it was actually next to an old mill."
    "A striking coincidence. Maybe it’s the old-fashioned style of the bar that entices her in, even across the boundaries of universes."
    "I grab my bag and head out."
    "The streets are eerily quiet on the way, save for a distance rumble that grows louder with each step. Another earthquake, brief but unsettling."
    "I steady myself, the vibrations feel like an omen, the kind of premonition you can’t ignore…"
    "And yet, I find myself like many other passersby ignoring it. I’ve already gotten used to the frequent earthquakes, but I still have this gnawing feeling that there’s something unusual about them."
    "I arrive at The Old Mill, the neon sign flickering like a dying star. The place looks either looks like it’s been waiting for me, or it’s just the kind of place that never changes." 
    "The bartender, a grizzled old mare with eyes like embers, watches me come in with a curiosity towards my unusual appearance but quickly it’s overshadowed by indifference."
    "I take note of the others at the bar. About ten people currently, and none of them are [rik]. I approach the counter, and the bartender looks up."
    mc "I heard [rik] was here earlier. Can you tell me where she went?"
    $ misc = "Bartender"
    misc "She was here, alright. Didn’t leave no address or nothing if that’s what you’re expecting. Just up and vanished."
    misc "Heavy drinker, that one. Some folks say she’s gone off the rails. Wasn’t pretty."
    "She wipes a glass with a wag, the movements so practiced and detached that she does it perfectly without breaking eye contact."
    "I look around and catch snippets of conversation from the patrons scattered about."
    $ misc = "Patron 1"
    misc "[rik]? Man, she was something back in the day. Used to be the pride of the city when the sports was back on. It’s a shame."
    $ misc = "Patron 2"
    misc "Tsk, now she’s just a drunk. City’s changed. No more games, no more fun. Only the military and the dark lands."
    misc "[rik]’s just another washed-up name." 
    "Their words drift to me, a testament to a time long past. To a city that has fallen into the hands of those who value power over pleasure, structure over spirit."
    "[rik], once a beacon of athletic prowess, already reduced to a relic of the past." 
    $ misc = "Patron 3"
    misc "You think you know [rik]? You don’t know a damn thing about her!"
    "I turn to see an orange mare standing not too far from me, her violet eyes blazing with intensity. She’s young, with an air of defiance."
    "The other patrons give her an uninterested glance and return to their drinks, somehow making me the target of this orange mare’s wrath by process of elimination."
    misc "[rik] works harder in a day than any of us have worked our entire lives! She’s a legend. I can’t stand people acting like she’s just a washed-up-has-been!"
    mc "I didn’t mean any disrespect. I’m just an old friend trying to find her."
    "Her eyes quickly soften, and she extends a fuzzy hand."
    misc "Sorry, about that! My name’s…"
    #Skye name input
    "Her anger seemed to melt away as fast as it appeared. Although it was replaced by a weariness etched into her features. She takes a seat on the barstool beside me."
    sky "Yeah, things have changed… The golden age of her career, when everyone agreed she was the top athlete, tragically cut short by some darkness nonsense."
    sky "She was the greatest. But this city’s got no room for sports anymore. Only thing keeping her afloat is the tabloids and endless drama."
    mc "How did you get to know her?"
    "[sky]’s gaze drops to the bar top. She traces an absent pattern with her fingers, lost in thought." 
    sky "I was her apprentice. She taught me everything I know."
    sky "Which means I’m equally shit out of luck because there’s nothing to train for. No competitions, no games. By the time competitions start again, we’ll be past our prime. Just a world that’s moved on without us."
    "This universe has taken so much from its people, left them scrambling to find meaning in a landscape that’s become increasingly hostile and indifferent."
    mc "I know what it’s like to feel like you don’t quite belong. Maybe that’s why I’m here. Trying to find something that makes sense." 
    sky "[rik] always said there’s kinship between those who have lost but keep trying…"
    sky "Which is exactly why I’m so pissed off!" 
    sky "[rik]’s given up! Just like that. Everything she worked for, everything she was… gone."
    sky "Just drowning in drink and self-pity. it’s like she’s forgotten what it means to fight, to actually live. There’s more to life than fame and trophies. Hell, there’s more to life than what this city’s become!"
    "I can see the struggle in her eyes, the deep anger at watching someone she admires lose their way."
    mc "You’re right. Losing your purpose, having it ripped away even – that’s a heavy blow. But giving up? That’s the easy way out."
    mc "If she’s willing to fight, there’s a chance to reclaim what she wants. Failing that, maybe there’s a chance to make a difference, to find new meaning."
    "[sky] leans in close, a spark of hope in her eyes. This actually breaks me out of my concentration as I realize just how cute she looks."
    sky "You get it! Hehe!"
    "The city outside is dark and indifference, but if I can get [rik] to join the Virtues, a team capable of potentially confronting the darkness that has tainted this world. It’s a chance not only for glory, but to return to her previous life."
    mc "There’s a group called the Virtues. Six powerful mares that are going to work under the Queen, and I’m hoping that in collaboration, they’ll be able to fight the darkness."
    mc "It might be the very thing she needs to pull herself up, a new purpose. If she’s willing to fight, if she’s willing to take that chance, there’s a place for her." 
    "[sky]’s eyes widen as she takes in the idea. The prospect of a new purpose, a new battle, seems to resonate with her. She’s caught between excitement and skepticism"
    sky "That sounds too good to be true. It’s exactly what she needs, and what she wants. If the darkness is gone, not only will she be heralded as a hero, but she can continue her glory days as an athlete." 
    "She pauses, taking a moment to gather her thoughts, then continues with a note of hesitation."
    sky "I was actually with [rik] here up until about half an hour ago. We didn’t part on the best of terms. She went home after a bit of a fight. But it’s not unusual for us to meet up for drinks. Perhaps the three of us could organize a meeting here, talk it over." 
    mc "That sounds like a good plan. We’ll meet up, talk things over. If [rik]’s willing to listen, this’ll be a huge opportunity for her, rather than another dead end."
    "With a wide grin, she reaches across the bar with a burst of energy and eagerly orders a drink for both of us without even asking."
    sky "You know, I’m really glad we ran into each other. It’s not every day someone comes along and actually gives a damn."
    sky "Here’s to new beginnings!"
    "She slides the glass across to me and I happily accept it. We toast, and as the night wears on, the conversation flows as easily as the booze."
    "[sky], with her vibrant energy, and tomboy charm, becomes the focus of my thoughts. She talks with a frankness that’s both refreshing and rare, her laughter ringing clear and unburdened."
    sky "So, what brought you to this part of town? I haven’t seen anyone quite like you around here."
    mc "I’m just trying to make sense of things"
    mc "I heard [rik] likes coming here, and it seemed like a thread worth following. And it seems like I ended up in good company."
    sky "Good company, huh? I suppose you’re not just talking about the drink."
    "Her playful tone was accompanied by a slight tilt of her head. I catch her gaze, her smile instantly widening as I do."
    mc "{i}Definitely{/i} not just the drink. It’s always great to meet someone that’s willing to speak their mind and actually listen. That’s not always what I expect from people in your industry."
    sky "Bahaha. Tell me about it. Everyone else’d only talk about the ‘old sports days.’"
    mc "But instead of wallowing in the past, you’re looking for a way forward. You surprised me."
    sky "Well, I suppose I have a way of doing that. Sometimes, it’s easier to put up a front than to deal with what’s underneath."
    "She looks down at her drink, the reflection of the bar’s light shimmering on the surface."
    mc "We all wear masks, don’t we? It’s the genuine moments that cut through, though. Like now."
    sky "You’re right about that. We’re all suffering. But it’s rare to find someone that sees through the façade and still wants to stick around."
    sky "I’ve had this exact conversation at least ten times before, but I’ve never had anyone actually interested in helping."
    sky "It’s always ‘Damn, I hope things get better!’, or even people trying to give me reasons for why I should actually give up."
    sky "And it’s not like I’m asking for a magical opportunity like the one you’re giving [rik]. I just wanted a little thought and support."
    sky "Makes me wonder, has [rik] had this conversation ten times before too? I think [rik] was let down too many times, and just gave up."
    mc "But [rik] had you, and I can tell that you never gave up. Not on her, not on yourself."
    sky "I wonder if support is really enough… Maybe now is the time for action."
    sky "You know, I’ve met a lot of people in my time. Most of them are either full of themselves or just out for a good time. But you—"
    sky "—You seem different. There’s something refreshing about you. It’s rare to find someone who doesn’t just see me as a ‘former athlete’ or a ‘celebrity.’"
    mc "Really? I didn’t even know you were famous."
    sky "Not as widely known as [rik], but yes, I was preparing to take the world by storm as another top flier, ‘full of potential’."
    "She gestures down to her toned body, and my eyes follow her hands as I soak in the detail. Although by the time my eyes return to her face, she’s smirking as if I wasn’t supposed to actually look." 

    mc "But even if I did know, I don’t think it’d make a difference. It’s easy to see beyond the labels when you’re talking to someone as real as you."
    sky "Hehe, so, other than saving washed-up athletes from themselves, what do you do for fun?"
    mc "I’m not originally from Arcadia, so I love reading the books or really any media produced here. Even your non-fiction reads like fiction to me. Anything out of the ordinary is enough to captivate me."
    "She rests her chin on her hand, her gaze fixed on me with a mixture of intrigue and amusement."
    sky "Books, huh? That’s actually pretty cool. I have a soft spot for the fantastical too. When I was younger, I used to get lost in stories of heroic quests and legendary battles."
    sky "For me, sports took over as a kind of reality where I could be that hero that tries their best to overcome impossible obstacles. At heart, I’m still a full-time nerd, I just focused that boundless energy."
    sky "But I admit, the flying did take over, I don’t read or watch as many things as I used to."
    sky "I could use an extra hour or two every day, but then I don’t know if I’d even make use of it effectively."
    mc "Ahh, I know what you mean. there’s always so much to do, that sometimes life can pass you by without you even realizing."
    sky "That’s certainly true, but it’s even worse for me, at times I’m just too tired or lazy to finish all the things I want to do."
    sky "By the time I finally finish training, or work, sometimes I just want to switch my brain off and go comatose for the rest of the evening."
    mc "Now that is very relatable."
    sky "Can you believe I bought a guitar that I can’t even play? I said I was going to practice for half an hour a day, and I did, at first, but… Why is it so hard… sometimes.. --- {i}Yawn{/i}."
    "The last word is broken up by a lengthy (and adorable) yawn that [sky] makes no effort to suppress."
    sky "It’s getting late. I should head back to my place…"
    sky "But, uhm... If you're up for it, you could come back to my place. It'd be nice to have some company. I mean, if you don't mind."
    "The invitation is wrapped in a shyness that contrasts sharply with the earlier fire in her eyes. It’s an offer veiled in indifference, but I can tell she wants me to come."
    mc "I’d like that. Lead the way, [sky]."
    "Her face lights up, a genuine smile breaking across her features. She reaches for her phone, tapping out her number with a quick, confident flourish before handing it to me."
    sky "Here. Just in case you want to keep in touch. I’ve got a feeling we’ll be seeing more of each other."
    "We leave The Old Mill together, the cool night air greeting us as we step out. The streets are quiet, the city’s heartbeat slow and steady beneath the starlit sky. As we walk, her hand brushes against mine, a touch that feels both natural and electric."
    "… Only ten minutes later…"
    "Her apartment is modest but inviting, a cozy space filled with the scattered remnants of a life lived with purpose. The walls are adorned with memorabilia, trophies, and photos—a testament to a past that refuses to be forgotten."
    "[sky] moves about with a relaxed confidence, her earlier shyness melting away in the familiarity of her home, and of course, the amount of alcohol in our systems."
    "She gestures to the couch, a casual invitation that feels surprisingly intimate."
    sky "Make yourself comfortable. I’ll get us something to drink. We can talk more, or just hang out. Whatever you prefer."
    "As she returns with drinks in hand, she hops down beside me and lifts her feet up. From where I’m sat, the view is admittedly quite lewd."
    "Just as the temptation to place my hand on her thigh grows, she makes the first move in the most unusual way."
    sky "Your, uhm, thingy is pretty different."
    "It takes me a moment to realize what she’s referring to, but by following her eyes it leads to my crotch."
    mc "I didn’t realize you were that interested!"
    sky "I know it’s supposed to be rude to stare, but…"
    sky "It gets bigger, right?"
    mc "Of course, significantly larger, actually."
    sky "Uhm… May I see it?"
    "I study her for a long moment, taking in the way her chest rises and falls with each breath, the way her hands fidget nervously in her lap."
    menu:
        "{i}Let her continue{/i}":
            "She’s caught between two worlds—one where she’s the confident tomboy who’s used to getting what she wants, and the other where she’s just a girl, curious and stepping into unknown territory. I decide to let her lead, to see how far she’s willing to go."
            "She reaches out slowly, her hand trembling just enough that I can see it. Her fingers brush against my shaft, light and tentative, testing the waters before she dives in."
            "There’s a tension in the way she breathes, her chest rising and falling with a rhythm that’s just a bit too fast."
            "She feels it respond, growing under her touch like a beast awakening from slumber."
            sky "Whoa, it’s… it’s really growing. I didn’t think it could get that hard."
            "Almost playing with it, she marvels at how it can feel so simultaneously soft, squishy, and hard."
            "Her hand moves more confidently now, fingers curling around the shaft and pulling the skin down. The cool air hits my tip, but it’s her warm touch that I feel most, her hand wrapping around me with an enthusiasm that surprises even her."
            sky "It’s like… I can feel your heartbeat through it. That’s so wild, but it’s kind of… I dunno, exciting?"
            "Her hand is soft, yet there’s a strength in her grip that I hadn’t expected. She finds a rhythm, her strokes long and deliberate, and I can feel the tension coiling inside me, a spring wound tight and ready to snap."
            "Her body is getting closer, so close that I can feel the warmth of her breath on my skin, the faint scent of something sweet lingering in the air between us."
            "There’s a quiet desperation in her now, a need that drives her movements faster, her grip tightening as she works to bring this to its inevitable conclusion. Her lips part slightly, a soft exhale slipping out, and I can see the way her own excitement is building, her body leaning closer to mine, as if drawn by some invisible force."
            "My breath hitches, a sharp intake that echoes in the quiet room, and I can see the effect it has on her. She bites her lip, her eyes darkening as she watches me, her hand moving faster, more determined. The tension inside me tightens, pulling me closer to that edge, and I can feel the moment approaching, that sweet, inevitable release just out of reach. "
            sky "I can tell you’re getting close, aren’t you? Just let go. I want to see it… I want to feel it."
            "She senses it too, her movements growing almost frantic now, her own breath coming in short, quick gasps. That fire is back in her eyes, a raw intensity that’s exhilarating, and I know that she’s as caught up in this as I am. There’s no going back now, no stopping what’s coming, and as her hand moves with a final, desperate urgency, I feel it—an explosion of sensation that rips through me, pulling me over that edge."
            play sound2 cum
            with c
            sky "There it is… I can feel it! Oh, wow, you’re really… that’s it, let it all out!"
            play sound2 cum
            with c
            "It’s like a release of everything—every tension, every worry—all of it crashing down in a wave of pure, blinding bliss. My body tenses, my breath catching in my throat, and for a moment, the world narrows to nothing but her hand, her touch, the feel of her fur against mine."
            "She leans back, her hand slipping away. But she doesn’t move away from me, if anything I can feel her lean closer."
            sky "Nnghh… [mc]…"
            mc "Yeah?"
            sky "I {i}really{/i} want to feel it in my ass…"
            mc "I think that was the absolute last thing I expected you to say."
            "Without another word, she straddles me, her body light as a feather. She doesn’t say anything, just reaches for my shaft once again, her fingers deft and quick."
            sky "Wow… it’s getting bigger already. I knew you had more in you. Guess I was right to be curious…"
            #non insertion sky1b
            "Once I’m erect, she turns her back to me now, and for a moment, I’m left staring at the smooth curve of her back down to the rounded shape of her firm butt. My eyes reach her butt just in time to see her rubbing her twitching pucker with a generous amount of lube."
            "She pauses, just for a heartbeat, as if giving me a moment to take it in, to process what’s happening. Then she leans forward, her hands bracing against the arm of the couch, and the movement is so natural, so fluid, that it takes me a moment to realize how close my tip is to her ass."
            sky "Is this okay for you? I’m saving the other side."
            mc "Ahaha, why don’t I just show you want I think?"
            "There’s no hesitation, no second-guessing. My hands finding her hips, the fur warm and soft beneath my fingers. She lets out a small moan, as I position myself behind her, her body squirming in response."
            play sound2 cum
            "The moment hangs, suspended in time, and then, with a slow, deliberate movement, I push forward into her ass. The sensation is immediate, intense, the tightness of her pucker surrounding me, drawing me in. She gasps and I can feel her muscles tensing, tightening around me."
            sky "Ooohh… I can feel every inch… damn, you’re filling me up perfectly."
            "I move slowly at first, her ass relaxing with each thrust and the heat of her body radiating back against mine. Her fingers and toes curl, as she pushes back against me, meeting my movements with a pace of her own."
            "[sky]’s breath comes in short, quick bursts, her body trembling with each movement. The tightness, the pressure, it’s drawing me closer to that second orgasm."
            "Her hips rock back against me, urging me on, and I respond in kind, moving with a rhythm that matches the frantic beat of our hearts. Even though I’m deep in her ass, there’s still an intimacy in this, a connection that goes beyond the physical, something that neither of us had anticipated when we met but both of us are lost in now."
            "I can feel the way her body responds, the way she pushes back, seeking more, craving each droplet of pleasure. It’s as if she’s testing her own limits, pushing herself to the brink, and I’m right there with her, caught up in the passion."
            sky "God, you’re so deep… I can’t get enough of this. I-I think I’m about to cum!"
            "She lets out a low, guttural moan as she reaches climax, her body shuddering beneath mine, and that sound—God, that sound—pushes me over." 
            sky "Yes, yes… right there… that’s it… give it all to me!"
            play sound2 cum
            "There’s no holding back now, no stopping what’s coming, and with a final, desperate thrust, I start to unload into her tight ass. A glorious, blinding finish that floods pleasure through me."
            "The release is intense, almost violent in its force, and I can feel excess of my cum spilling out of her, dripping down her thighs."
            "For a moment, we stay like that, our bodies still connected, the world around us fading into nothing."
            "Then, slowly, as my cock shrunk, I pulled out of her ass, my heart still pounding in my chest."
            sky "{i}Pant, pant{/i} You really delivered. I didn’t expect it to feel this good."
            "She laughs, a soft, almost shy sound, and I can’t help but smile at the sight of her, flushed and beautiful. She got on top of me and continued to cuddle, her arms threading around my body with an ease that feels natural."
        "{i}Excuse yourself{/i}":
            sky "That’s okay. It was a strange thing to ask."
            "Her smile not skipping a beat, she leans back, and the topic turns to other things as we cuddle together on the sofa." 
            "Eventually, it grows late, and the evening begins to wrap up."
    sky "I had a really great time tonight. We should definitely do this again."
    mc "I’d like that."
    sky "I’ll send you a text when I’ve wrangled [rik] and I’m ready to meet, okay?"
    mc "Sounds good. I’m looking forward to it."
    "[sky]’s eyes twinkle as she gives my hand a final, affectionate squeeze before letting go."
    "I let myself out as [sky] happily dozes off on her couch."
    "Once I return to [mox]’s apartment, I find her in almost the exact same pose, lazily scrolling her phone."
    mox "Oh, hey! Did you end up finding [rik]?"
    mc "The second-best thing. I found her apprentice, told her my plan, and she’ll set a meeting up for the three of us."
    mox "You’re a real social wizard, you know that? I wouldn’t even be surprised if you turned around and told me you slept with this new girl too." 
    if sky1 == 0:
        mc "Actually, I didn’t!"
        mox "Huh, I’m somehow still surprised."
        mc "I thought you said you wouldn’t be surprised."
        mox "Somehow, you always find new ways to surprise me!"
    else:
        mc "Oh, uh… {i}I did{/i}!"
        mox "YOU DID?!"
        mc "You said you wouldn’t be surprised!"
        mox "Gah, somehow, you find new ways to surprise me!"
    jump newday
